on: [push]

name: Create Release

jobs:
  build:
  - name: release
    uses: actions/create-release@v1
    id: create_release
    with:
      draft: false
      prerelease: false
      release_name: v0.0.1
      tag_name: v0.0.1
    env:
      GITHUB_TOKEN: ${{ github.token }}
