name: 'Deployer setup'
description: 'Setup'
inputs:
  SSH_HOST:
    description: 'Host SSH'
    required: true
  SSH_PORT:
    description: 'Port SSH'
    required: false
    default: '22'
  SSH_USER:
    description: 'User SSH'
    required: true
  SSH_KEY:
    description: 'Key SSH'
    required: true
  RELEASE_NAME:
    description: 'Name release'
    required: true
runs:
  using: 'docker'
  image: '../Dockerfile'
  args:
    - setup
    - ${{ inputs.SSH_HOST }}
    - ${{ inputs.SSH_PORT }}
    - ${{ inputs.SSH_USER }}
    - "${{ inputs.SSH_KEY }}"
    - ${{ inputs.PATH_DEPLOY }}
    - ${{ inputs.RELEASE_NAME }}
branding:
  icon: 'upload-cloud'
  color: 'blue'
