name: 'Deployer lock'
description: 'Lock'
inputs:
  SSH_HOST:
    description: 'Host SSH'
    required: true
  SSH_PORT:
    description: 'Port SSH'
    required: false
    default: '22'
  SSH_USER:
    description: 'User SSH'
    required: true
  SSH_KEY:
    description: 'Key SSH'
    required: true
  PATH_DEPLOY:
    description: 'DEPLOY PATH'
    required: true
  USERNAME:
    description: 'Username deployment'
    required: true
runs:
  using: 'docker'
  image: '../Dockerfile'
  args:
    - lock
    - ${{ inputs.SSH_HOST }}
    - ${{ inputs.SSH_PORT }}
    - ${{ inputs.SSH_USER }}
    - "${{ inputs.SSH_KEY }}"
    - ${{ inputs.PATH_DEPLOY }}
    - ${{ inputs.USERNAME }}
branding:
  icon: 'upload-cloud'
  color: 'blue'
